[package]
name = "oxc_parser_napi"
version = "0.0.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
description.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]
test = false
doctest = false

[dependencies]
oxc = { workspace = true, features = ["napi", "serialize", "parser"] }
oxc_module_lexer = { workspace = true }

napi = { workspace = true, features = ["async"] }
napi-derive = { workspace = true }
self_cell = "1.0.4"
serde_json = { workspace = true }
string_wizard = { version = "0.0.22", features = ["source_map"] }

[package.metadata.cargo-shear]
ignored = ["napi"]

[build-dependencies]
napi-build = { workspace = true }
